#
#
#================================================================
#   
#   
#   文件名称：config.mk
#   创 建 者：肖飞
#   创建日期：2021年08月26日 星期四 11时10分19秒
#   修改日期：2021年10月11日 星期一 22时31分29秒
#   描    述：
#
#================================================================

CONFIG_LIST := 

CONFIG_LIST += CONFIG_DEVICE_TYPE_AC

CONFIG_LIST += CONFIG_STORAGE_OPS_25LC1024
#CONFIG_LIST += CONFIG_STORAGE_OPS_24LC128
#CONFIG_LIST += CONFIG_STORAGE_OPS_W25Q256

#CONFIG_LIST += CONFIG_NET_CLIENT_PROTOCOL_UDP
CONFIG_LIST += CONFIG_NET_CLIENT_PROTOCOL_TCP
#CONFIG_LIST += CONFIG_NET_CLIENT_PROTOCOL_TLS

#CONFIG_LIST += CONFIG_NET_CLIENT_REQUEST_DEFAULT
CONFIG_LIST += CONFIG_NET_CLIENT_REQUEST_SSE
#CONFIG_LIST += CONFIG_NET_CLIENT_REQUEST_OCCP_1_6

#CONFIG_LIST += CONFIG_CHARGER_CHANNEL_PROXY_REMOTE
#CONFIG_LIST += CONFIG_CHARGER_CHANNEL_PROXY_LOCAL

#CONFIG_LIST += CONFIG_CHARGER_BMS_HANDLER_GB
CONFIG_LIST += CONFIG_CHARGER_BMS_HANDLER_AC

#CONFIG_LIST += CONFIG_CHANNELS_POWER_MODULES_NATIVE

$(foreach config_item,$(CONFIG_LIST),$(eval $(config_item) := $(subst CONFIG_,,$(config_item))))

CONFIG_CFLAGS := $(subst CONFIG_,-D,$(CONFIG_LIST))
